### PR TITLE
[WIP] Fix tests

### LINKED ISSUE #52: Fixing the tests
I'd like to add a PR which fixes #51 but it's not possible at the moment because the tests wouldn't pass, even if I made the right change. More generally, at the moment we can't really do any meaningful pull request reviews because the tests are failing. 

@andrewgsavage I think you have the best overview of this, can you see a way to get the tests going again? For example, could we split #48 into two: 1. fix tests, 2. fix offset units? That would help things move and give a clearer sense of what functionality is still not yet implemented (because it's waiting on fixes to e.g. https://github.com/pandas-dev/pandas/issues/35131

### PR DESCRIPTION
**Pull request by andrewgsavage**
Made a start at getting tests working again.

- [x] Closes #52 
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by hgrecco** [comment]
To run the linters, my suggestion is that you do:
```
$ pip install pre-commit
$ pre-commit install  # in the pint-pandas git folder
$ pre-commit run --all-files 
```

I have found that this much more reliable than using black/isort/flake from command line as we were doing this before.

**Comment by hgrecco** [comment]
I added a PR template!

**Comment by znicholls** [comment]
@andrewgsavage if you think this could be slow, would an easier first step be to just mark things as xfail then we work our way back through bit by bit in subsequent PRs? I'm just concerned that progress will be held up (e.g. my fiddling with pandas is_list_like in #59) if we try and solve everything here (which could be hard).

**Comment by znicholls** [comment]
We can add 'closes #52' to the description right?

**Comment by andrewgsavage** [comment]
> @andrewgsavage if you think this could be slow, would an easier first step be to just mark things as xfail then we work our way back through bit by bit in subsequent PRs? I'm just concerned that progress will be held up (e.g. my fiddling with pandas is_list_like in #59, I seem to have caught the attention of the pandas devs so am keen to capitalise) if we try and solve everything here (which could be hard).

Yea that's fair, some could take a while and I won't know till I try

**Comment by andrewgsavage** [comment]
@hgrecco this is ready, will get to the remaining tests in another PR

**Pull request merged**
