### PR TITLE
Move files from pint to pint-pandas + Duck typed PintType

### PR DESCRIPTION
**Pull request by andrewgsavage**
This PR moves the pandas interface files from pint to this repo, and stores the units in the PintType as opposed to storing a quantity in the PintArray previously.

I've updated the example notebook to use the duck typed PintType. 
https://github.com/andrewgsavage/pint-pandas/blob/duck_typed/notebooks/Pandas_support.ipynb
(This uses my pint branch, https://github.com/hgrecco/pint/pull/746/commits/61b44aec550c7ff34c9b20fb3000c8d19fc04706)

The pytest Tests are run in here and passing again, bar the xpassed ones. Haven't looked at coverage and not sure how it works!

- [x]  remove pandas interface from main pint repo, point travis to main pint repo instead of mine.
- [ ] coverage
- [x] Accredit @znicholls

### CODE REVIEW

**Comment by hgrecco** [comment]
This is progressing nicely. Please ping me when you want me to merge or look at it in more detail.

**Comment by andrewgsavage** [comment]
@hgrecco I think this is ready to look at. 

I've got the coverage running, but not sure how to get it to compare to previous builds

**Comment by andrewgsavage** [comment]
@znicholls would you like the tests and notebooks again? I think that's how we had it before. 
Could you give me a hand with the commands for squashing / removing the tests/notebooks? 

Ah there's a release of pandas out now so can use that

**Comment by hgrecco** [comment]
@andrewgsavage done

**Comment by znicholls** [comment]
> @znicholls would you like the tests and notebooks again? I think that's how we had it before.
> Could you give me a hand with the commands for squashing / removing the tests/notebooks?

Yep sure! There's a few issues to cover so I've put them in #6, #7 . 

In terms of workflow, I'll make PRs into andrewgsavage/pint-pandas. I'll add a PR with the new files into https://github.com/hgrecco/pint-pandas/pull/5 now

**Pull request closed without merging**
