### PR TITLE
Mark tests failing due to iter issues

### PR DESCRIPTION
**Pull request by andrewgsavage**
Trying to get tests to green before any other changes, but there's one that's passing on my machine but not on travis..

### CODE REVIEW

**Comment by andrewgsavage** [comment]
@hgrecco this is ready now

**Comment by andrewgsavage** [comment]
any idea why bors is timing out?

**Comment by znicholls** [comment]
@andrewgsavage are we waiting on this before tackling #39 (trying to get my head around where I got to with https://github.com/pandas-dev/pandas/pull/35127)

**Comment by andrewgsavage** [comment]
I don't think there's anything I can do on this, it needs @hgrecco to get bors working
This has been merged into https://github.com/hgrecco/pint-pandas/tree/staging

**Pull request merged**
