### PR TITLE
Support numpy ufuncs and pandas-style sum/mean/etc' (via _reduce)

### LINKED ISSUE #16: PintArray should implement Series._reduce
PintArray is missing is an implementation of `pd.Series._reduce`:
https://github.com/pandas-dev/pandas/blob/cf25c5cd3ab1f647f780167df622c74b737fa8f5/pandas/core/series.py#L3709, to support reduction functions like min/max/sum/prod.
 
I'm pretty psyched about this new EA integration with pandas, I've wanted something like this for a long time...  good job! :+1:

### PR DESCRIPTION
**Pull request by pilkibun**
closes #16 

Tests Pending, but I'm currently using this.

### CODE REVIEW

**Comment by hgrecco** [comment]
@andrewgsavage Take a look at this

**Comment by pilkibun** [comment]
There's still a missing bit about supporting ops like `round`, but the details are a little murky on the pandas EA side, and many of the series functions on that side do object coercions. 

I'm talking with pandas, but it'll take time.

**Comment by andrewgsavage** [comment]
Seems fine. Should add tests. 

@pilkibun since you seem interested you should look at https://github.com/hgrecco/pint/pull/764 which implements `__array_function__ ` for Quantity. After Quantity gets split it may be possible for the PintArray to inherit from Quantity preventing the need to delegate.

**Comment by pilkibun** [comment]
> After Quantity gets split it may be possible for the PintArray to inherit from Quantity preventing the need to delegate.

Delegating to `Quantity` is simple enough, while inheriting `Quantity` may raise unforseen issues, like name collisions with current or future addition to `ExtensionArray`. And, I'm not sure what the benefits would be. Wouldn't you still have to reimplement `array_ufunc` `__array_function__`/numpy methods and `_reduce` so that they return a `PintArray` instead of a `Quantity`? Or do you plan to turn  `_Quantity` itself into a pandas `ExtensionDType`? in which case pint will no longer be independent of pandas. Seems sticky. Also, "People say" you should "Prefer Composition to Inheritance", because of these kind of issues, don't they?

**Comment by andrewgsavage** [comment]
Yes we'd have to work around those issues when they come up.

I think we'd only implement array_ufunc  etc once.  A structure like this would let us implement them in QuantitySequenceMixin and we'd use `self.__class__` to return a PintArray or QuantitySequence.
https://docs.google.com/presentation/d/1AXwyOq4gKPO3Qt17P-RoluAFHQXDMXZXoVvDzZpjlhU/edit#slide=id.p

**Comment by pilkibun** [comment]
Pandas is still seeing significant churn about method dispatch, this will perhaps need to be rewritten when they stabilize in a version or two. Closing.

**Pull request closed without merging**
