### PR TITLE
Reimplement Reduce (Series.min, max..)

### PR DESCRIPTION
**Pull request by andrewgsavage**
Fixes https://github.com/hgrecco/pint-pandas/issues/45

### CODE REVIEW

**Comment by cfobel** [comment]
@andrewgsavage, thanks for your fix!

Is there anything I can do to help get this merged?

**Comment by cfobel** [comment]
Thanks @hgrecco! 🎉

**Comment by hgrecco** [comment]
Thank you all for the great work!

**Comment by cfobel** [comment]
@hgrecco, just to clarify, I just chimed in here 🙂 Thanks go to @andrewgsavage for submitting the pull request!

**Comment by hgrecco** [comment]
Yes, but your comment made me realize that I did a very silent merge 😄

**Pull request merged**
