### PR TITLE
Bugfix/fix 165 fill value must be scalar

### LINKED ISSUE #165: "ValueError: fill_value must be a scalar" when concatenating columns requiring fill
The following MWE shows the issue:
```python
import pandas as pd
import pint_pandas

a = pd.Series(index=[1,2],data=pint_pandas.PintArray([0.,1.], u.mm))
b = pd.Series(index=[2,3],data=pint_pandas.PintArray([2.,3.], u.s))

pd.concat([a,b],axis="columns")
```
With "normal" pint columns, the code works as expected. I partially traced the error down to https://github.com/hgrecco/pint-pandas/blob/c58a7fcf9123eb65f5e78845077b205e20279b9d/pint_pandas/pint_array.py#L475
which seems to create a 0-d numpy array instead of a numpy scalar.

This may be an impact of a recent change in either pint_pandas or numpy; I already observed that my `int(round(some_quantity/other_quantity_of_same_dim))` started to fail and now require a `int(round(float(...)))` construct.

The relevant versions in my environment are:
```
numpy: 1.23.5
pandas: 1.5.1
pint: 0.20.1
pint_pandas: 0.3
```

### PR DESCRIPTION
**Pull request by burnpanck**
- [x] Closes #165
- [x] Executed `pre-commit run --all-files` with no errors
- [x] The change is fully covered by automated unit tests
- [ ] ~Documented in docs/ as appropriate~
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by andrewgsavage** [comment]
Is that the only place you encouter issues with `force_ndarray_like = True`? Would it be worth running all the pandas extension tests with `force_ndarray_like = True`?

**Comment by burnpanck** [comment]
Indeed, it may be reasonable to run the whole test-suite both with and without `force_ndarray_like = True`. Without this fix, many of the tests fail, but it always appeared to be the same error; missing values is an important feature within pandas. I think all issues may be fixed now, but I actually didn't run the whole test-suite with that flag after the fix at all. Do you know of a good way of passing a "feature flag" to a global `pytest` fixture, so that we can just simply run the whole test-suite twice?

**Comment by andrewgsavage** [comment]
I'm not aware of one, and the options I found googling didn't look suitable. I'll open a new issue for it.

**Pull request merged**
