### PR TITLE
Add release infrastructure

### LINKED ISSUE #8: Upload to pypi
Is there anything else we'd like to do before uploading it to pypi?

### PR DESCRIPTION
**Pull request by znicholls**
Closes #8 #22

### CODE REVIEW

**Comment by znicholls** [comment]
@hgrecco and @andrewgsavage this adds the docs and basic infrastructure for releasing on pypi and conda (it's based on another project of mine, https://gitlab.com/netcdf-scm/netcdf-scm, specifically https://gitlab.com/netcdf-scm/netcdf-scm/-/blob/master/docs/source/development.rst).

In short, it means that releasing a new version is as simple as `git tag -vX.Y.Z && make publish-on-pypi` if you want it to be (although normally doing a few extra checks is worth it). If we get pint-pandas on PyPI, I'm happy to then put it on conda (should be simple, same idea as https://github.com/conda-forge/staged-recipes/pull/11343). 

Any questions please shout out!

**Comment by znicholls** [comment]
I'm not sure why the tests are failing btw

**Comment by hgrecco** [comment]
I use [zest.releaser](https://zestreleaser.readthedocs.io/en/latest/) and I am very happyt about it. 
Not only it uploads it to pypi but does all sorts of checks before doing it to verify that everything is fine.

**Comment by znicholls** [comment]
ok great, is a pypi release possible then? Do you want to use this PR as a base or just take care of it yourself?

**Comment by bilderbuchi** [comment]
You apparently have "dist: trusty" in the CI config, that is 14.04, i.e. a 6 year old Ubuntu version. Does Travis still support that in their images? That seems worthwhile to check. I guess at least using 18.04 could maybe fix the issue.

**Comment by hgrecco** [comment]
I will take part of this PR and the we work on that. Thanks a lot!

**Comment by znicholls** [comment]
Awesome I see you’ve made lots of progress in master so will close this, can reopen as needed. Cheers!

**Comment by hgrecco** [comment]
Actually ... thank you for kick starting this! I am trying to bump to pandas to 1.0.4 and fix all tests. I will open another issue for this

**Pull request closed without merging**
