### PR TITLE
Support for Pandas 1.5/1.6

### LINKED ISSUE #120: Experimental status?
I'm just curious what would be needed for this repo to drop the "experimental" status attached to it? ;)

### LINKED ISSUE #128: UnitStrippedWarning, simple case
Weird behavior using pandas 1.4.2, pint 0.19.2, pint-pandas 0.2.

I've seen many issues related to UnitStrippedWarning, but this is a simple case taken from the pint-pandas github page. It should work without a warning, right?

I'm getting these warnings whenever I create pd.Series with a pint dtype. Can anyone explain how to fix these other than ignoring the warnings?

```
import pandas as pd
import pint_pandas
s = pd.Series([1., 2., 2., 3.], dtype="pint[lbf ft]")
s
Out[5]: 
0    1.0
1    2.0
2    2.0
3    3.0
dtype: pint[foot * force_pound]
/Volumes/Plevin1TB/Software/anaconda3/envs/opgee/lib/python3.8/site-packages/pint_pandas/pint_array.py:648: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  return np.array(qtys, dtype="object", copy=copy)

# Even stranger: every subsequent expression generates this warning

"anything"
Out[6]: 'anything'
/Volumes/Plevin1TB/Software/anaconda3/envs/opgee/lib/python3.8/site-packages/pint_pandas/pint_array.py:648: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  return np.array(qtys, dtype="object", copy=copy)
```

### PR DESCRIPTION
**Pull request by andrewgsavage**
- [x] Closes #128 #125 #117 #113 #93 #26 
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

Probably closes #120 

This is running locally, with https://github.com/hgrecco/pint/pull/1596. Quite a few additional tests passing!
This is following the change to is_list_like in pandas, so allows constrcutors and setitem to work.

### CODE REVIEW

**Comment by andrewgsavage** [comment]
I've pointed this to my pint branch which adds ndim for Quantity, and my pandas branch which changes makes assert...equal recognise pint Quantitys as scalar. This is down to 
=========== 489 passed, 11 xfailed, 7 xpassed, 6 warnings in 11.20s ============
It was previously 
========== 433 passed, 64 xfailed, 8 xpassed, 246 warnings in 24.09s ===========

**Comment by andrewgsavage** [comment]
That's all the tests working with, the exception of the ones xfailed in pandas!

**Comment by andrewgsavage** [comment]
some issue with python 3.11 installing pyarrow so I'll leave that out for another PR.

**Comment by andrewgsavage** [comment]
This is ready now. @hgrecco Could you take a look at it?

I have set it to use my fork of pandas with branches for 1.5.x and 1.6.x to get around the assert_series_equal issue (pint scalars are recognised as iterable in a testing function). I've got a pandas issue and PR for this.

Is it better to have the affected tests xpassed, or to use my branches? 
I'm leaning towards using my branches as this lets us run these tests and know if any changes cause behaviour to change.

**Comment by hgrecco** [comment]
I have review it and I like the code. Should I release a new pint-pandas version now?

I agree that you should use your branches for testing

**Comment by andrewgsavage** [comment]
OK great, I'll merge this and #132 and then you can release a new version.

**Pull request merged**
